AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'course-app

  Sample SAM Template for course-app

  '
Globals:
  Function:
    Runtime: python3.8
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
    MemorySize: 128
    Timeout: 5
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: course_id
        AttributeType: S
      - AttributeName: teacher
        AttributeType: S
      KeySchema:
      - AttributeName: course_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
      GlobalSecondaryIndexes:
      - IndexName: Teacher-index
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          WriteCapacityUnits: 1
          ReadCapacityUnits: 2
        KeySchema:
        - AttributeName: teacher
          KeyType: HASH
      TableName:
        Fn::Sub: ${AWS::StackName}-courses
  GetCourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://samsls/f4617a80a3c69739d7958c84619c0cfa
      Handler: get.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCourse:
          Type: Api
          Properties:
            Path: /course/{course_id}
            Method: get
  PostCourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://samsls/f4617a80a3c69739d7958c84619c0cfa
      Handler: post.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCourse:
          Type: Api
          Properties:
            Path: /course
            Method: post
  UpdateCourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://samsls/f4617a80a3c69739d7958c84619c0cfa
      Handler: update.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        UpdateCourse:
          Type: Api
          Properties:
            Path: /course/{course_id}
            Method: put
  Deletecourse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://samsls/f4617a80a3c69739d7958c84619c0cfa
      Handler: delete.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        DeleteCourse:
          Type: Api
          Properties:
            Path: /course/{course_id}
            Method: delete
  UpdateTeacherName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://samsls/f4617a80a3c69739d7958c84619c0cfa
      Handler: kinesis-update-teacher.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream:
              Fn::GetAtt:
              - StreamConsumer
              - ConsumerARN
            BatchSize: 5
            StartingPosition: LATEST
  Stream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: stream-test
      ShardCount: 1
  StreamConsumer:
    Type: AWS::Kinesis::StreamConsumer
    Properties:
      StreamARN:
        Fn::GetAtt:
        - Stream
        - Arn
      ConsumerName: TestConsumer
